swagger: '2.0'
info:
  version: 1.0.0
  title: bamservices-api
  description: BAMSERVICES Api
basePath: /api/v1
tags:
  
consumes:
  - application/json
produces:
  - application/json

definitions:



paths:
  